### ISSUE TITLE
Issue when "Add record"

### ISSUE THREAD

**Issue by apazosg** [Bonitasoft-Community/page_moonrover#1]
Hello, after installing this app on my Pre server and trying to insert some values on a new row I got this issue and I'm not sure how to resolve it:
Exception remove[CustomPageMoonRover-2.3.0.jar]:org.bonitasoft.engine.command.DependencyNotFoundException: USERNAME=administrador | org.bonitasoft.engine.dependency.SDependencyNotFoundException: Dependency with name CustomPageMoonRover-2.3.0.jar does not exist.+Exception remove[bonita-event-1.7.0.jar]:java.io.FileNotFoundException: /opt/Bonita/BonitaCommunity-7.11.1/server/temp/bonita_portal_29919@BonitaSoft/tenants/1/pages/custompage_moonrover/lib/bonita-event-1.7.0.jar (No existe el archivo o el directorio)+Exception remove[bonita-properties-2.4.0.jar]:java.io.FileNotFoundException: /opt/Bonita/BonitaCommunity-7.11.1/server/temp/bonita_portal_29919@BonitaSoft/tenants/1/pages/custompage_moonrover/lib/bonita-properties-2.4.0.jar (No existe el archivo o el directorio)+Registering...

**Comment by pierre-yves-monnet** [comment]
Hello,
I reproduce it. Hold on.

**Comment by pierre-yves-monnet** [comment]
The point is that in 7.10, the BDM API changed, and now, when we persist a BDM via API, we faced a TransactionNotOpenned.
I will see with the R&D what is the new rule, and if this rule is compatible from 7.8 to 7.11. If not, a direct SQL Order will be done in the database.
This method will need time to be implemented.

**Comment by apazosg** [comment]
Sorry I couldn't get back to you earlier.

I got the error on 7.11 when I tryed to insert new values or update existing ones. 
Guess it's happening because of the BDM API change you mentioned on the last comment. 

Thank you for your time, and all the awesome contributions you have done. Please tell me if I can help you with anything.
Take care.

**Comment by pierre-yves-monnet** [comment]
Hello, this is fixed in 2.3.1
Thank !
